[tool.poetry]
name = "urban-palm-tree"
version = "0.1.0"
description = "Your project description goes here."
authors = ["Your Name"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11"
pyobjc = "^10.2"
pyobjc-framework-screencapturekit = "^10.2"
pyscreenshot = "^3.1"
pillow = "^10.3.0"
